### PR TITLE
Getting started with data science article

### PR DESCRIPTION
**Pull request by TreeinRandomForest**
Adding article from google chat about getting a high-level overview of data science

### CODE REVIEW

**Review by aakankshaduggal — APPROVED** [review]
Thank you so much @TreeinRandomForest :D 
/lgtm
/approve

**Comment by suppathak** [comment]
Loved the article @TreeinRandomForest. A concise guide for Data Science Aspirants. :)

**Review by oindrillac — APPROVED** [review]
/lgtm
/approve

**Comment by TreeinRandomForest** [comment]
thank you all! @aakankshaduggal @suppathak @oindrillac :)

**Pull request merged**
